#+title: Curriculum Vitae

#+HTML: This is the html version of my CV.
#+HTML: The PDF version can be found <a href="assets/cv.pdf">here</a>.
#+HTML: (They are the same.)

* Meta information :noexport:
- Run =build-cv.el= to get the PDF
* CV Tasks :noexport:
** TODO Add FastSync Patent
Created: [2024-09-08 Sun]
* Research Interests
My interests are /Byzantine fault-tolerant distributed systems/ and /applied cryptography/.
My work aims at developing and evaluating cryptographic solutions for secure, fault-tolerant distributed systems.
My current research focuses on energy-efficient consensus protocols in network settings such as synchronous, asynchronous, and all intermediate models; fault-tolerant cryptographic protocols such as PVSS and Random Beacons and Private set intersection.
* Education
@@latex: \item @@ *Purdue University, West Lafayette*
@@latex: \hfill @@ /(2018-2023)/\\
    Advisor: Aniket Kate\\
    Ph.D., Department of Computer Science

@@latex: \item @@ *National Institute of Technology Karnataka, Surathkal*
@@latex: \hfill @@ /(2014-2018)/\\
    Bachelor of Technology, Information Technology
* Work Experience
*Visa Research, Foster City* @@latex: \hfill @@ (Aug 2023 - Present)\\
/Staff Research Scientist/ @@latex: \hfill @@ /(Anderson Nascimento)/


*Visa Research, Palo Alto* @@latex: \hfill @@ (May 2022 - Aug 2022)\\
/Ph.D. Research Intern/ @@latex: \hfill @@ /(Mahdi Zamani)/
#+begin_export latex
\begin{list}{$\cdot$}{\leftmargin=0em}
\itemsep -0.5em \vspace{-0.5em} % Compress items in list together for aesthetics
#+end_export
@@latex: \item @@ @@html: - @@ Developed /FastSync/: an efficient blockchain synchronization protocol @@html: <br> @@
@@latex: \item @@ @@html: - @@ Developed an efficient partially synchronous sharding protocol and implemented Instachain
#+begin_export latex
\end{list}
\vspace{0.5em} % Some space after the list of bullet points
#+end_export

*VMware Research, Remote* @@latex: \hfill @@ (May 2021 - Aug 2021)\\
/Research Intern/ @@latex: \hfill @@ /(Alin Tomescu, Ittai Abraham)/
#+begin_export latex
\begin{list}{$\cdot$}{\leftmargin=0em}
\itemsep -0.5em \vspace{-0.5em} % Compress items in list together for aesthetics
#+end_export
@@latex: \item @@ @@html: - @@ Built a prototype of anonymous token system using Concord-BFT @@html: <br> @@
@@latex: \item @@ @@html: - @@ Developed /quick-pay/: a one-round trip low-latency payment system @@html: <br> @@
@@latex: \item @@ @@html: - @@ Developed a two-phase lock-free sharding solution using quick-pay
#+begin_export latex
\end{list}
\vspace{0.5em} % Some space after the list of bullet points
#+end_export

*Purdue University, West Lafayette* @@latex: \hfill @@ (Aug 2018 - Aug 2023)\\
/Graduate Research Assistant/ @@latex: \hfill @@ /(Aniket Kate)/
#+begin_export latex
\begin{list}{$\cdot$}{\leftmargin=0em}
\itemsep -0.5em \vspace{-0.5em} % Compress items in list together for aesthetics
#+end_export
@@latex: \item @@ @@html: - @@ Researching energy efficient Byzantine fault tolerant consensus protocols. @@html: <br> @@
@@latex: \item @@ @@html: - @@ Developed mathematical models for protocol optimization to improve energy efficiency. @@html: <br> @@
@@latex: \item @@ @@html: - @@ Implemented, evaluated, and simulated cryptographic and distributed system protocols.
#+begin_export latex
\end{list}
\vspace{0.5em} % Some space after the list of bullet points
#+end_export

*Indian Statistical Institute, Kolkata* @@latex: \hfill @@ (July 2017 - December 2017)\\
/Undergraduate Research Fellow/ @@latex: \hfill @@ /(Sushmitha Ruj)/
#+begin_export latex
\begin{list}{$\cdot$}{\leftmargin=0em}
\itemsep -0.5em \vspace{-0.5em} % Compress items in list together for aesthetics
#+end_export
@@latex: \item @@ @@html: - @@ Designed a storage auditing library based on compact proofs of retrievability. @@html: <br> @@
@@latex: \item @@ @@html: - @@ Implemented new transactions on an Ethereum client to build a publicly verifiable data-storage system.
#+begin_export latex
\end{list}
\vspace{0.5em} % Some space after the list of bullet points
#+end_export

*Morgan Stanley, Bangalore* @@latex: \hfill @@ (May 2017 - July 2017)\\
/Software Analyst/
#+begin_export latex
\begin{list}{$\cdot$}{\leftmargin=0em}
\itemsep -0.5em \vspace{-0.5em} % Compress items in list together for aesthetics
#+end_export
@@latex: \item @@ @@html: - @@ Worked on evaluating an elastic-search visualization plugin for the LevelDB database.
#+begin_export latex
\end{list}
\vspace{0.5em} % Some space after the list of bullet points
#+end_export

*Indian Institute of Science, Bangalore* @@latex: \hfill @@ (May 2016 - July 2016)\\
/Indian Academy of Sciences Summer Research Fellow/ @@latex: \hfill @@ /(C. E. Veni Madhavan)/
#+begin_export latex
\begin{list}{$\cdot$}{\leftmargin=0em}
\itemsep -0.5em \vspace{-0.5em} % Compress items in list together for aesthetics
#+end_export
@@latex: \item @@ @@html: - @@ Evaluated Pollard's rho, William's $p+1$, $p-1$ factorization, and elliptic curve factorization methods for efficient batch factorization of numbers generated during the sieving phase of GGNFS.
#+begin_export latex
\end{list}
\vspace{0.5em} % Some space after the list of bullet points
#+end_export

* Publications
#+begin_export latex
\vspace{0.5em}
#+end_export
1. <<lite-pot>> /Lite-PoT: Practical Powers-of-Tau Setup Ceremony./
   *CCS 2025.*
   Lucien K. L. Ng, Pedro Moreno-Sanchez, Mohsen Minaei, Panagiotis Chatzigiannis, *Adithya Bhat*, Duc V. Le.
   [[https://arxiv.org/pdf/2503.04549][eprint]]
2. <<SyncDKG>> /Synchronous Distributed Key Generation without Broadcasts./
   *Journal of Cryptology 2024*.
   Nibesh Shrestha, *Adithya Bhat*, Kartik Nayak, Aniket Kate.
   [[https://doi.org/10.62056/ayfhsgvtw][journal]] [[https://eprint.iacr.org/2021/1635][eprint]]
3. <<SensorBFT>> /SensorBFT: Fault-Tolerant Target Localization using Voronoi Diagrams and Approximate Agreement./
   *ICDCS 2024*.
   Akhil Bandarupalli, *Adithya Bhat*, Somali Chaterji, Michael K. Reiter, Aniket Kate, Saurabh Bagchi.
   [[https://www.computer.org/csdl/proceedings-article/icdcs/2024/860500a186/1ZCgEXQYbZe][conference]] [[https://reitermk.github.io/papers/2024/ICDCS.pdf][eprint]]
4. <<Delphi>> /Delphi: Efficient Asynchronous Approximate Agreement for Distributed Oracles./
   *DSN 2024*.
   Akhil Bandarupalli, *Adithya Bhat*, Saurabh Bagchi, Aniket Kate, Chen-Da Liu-Zhang, and Michael K. Reiter.
   [[https://ieeexplore.ieee.org/abstract/document/10647006][conference]] [[https://arxiv.org/pdf/2405.02431][eprint]]
5. <<HashRand>> /HashRand: Efficient Asynchronous Random Beacon without Threshold Cryptographic Setup./
   *CCS 2024*.
   Akhil Bandarupalli, *Adithya Bhat*, Saurabh Bagchi, Aniket Kate, and Michael Reiter.
   [[https://dl.acm.org/doi/abs/10.1145/3658644.3670326][conference]] [[https://eprint.iacr.org/2023/1755.pdf][eprint]]
6. <<Tor>> /Attacking and Improving the Tor Directory Protocol./
   *IEEE S&P 2024*.
   Zhongtang Luo, *Adithya Bhat*, Kartik Nayak, and Aniket Kate.
   [[https://ieeexplore.ieee.org/abstract/document/10646693][conference]] [[https://zhtluo.com/paper/Attacking_and_Improving_the_Tor_Directory_Protocol.pdf][eprint]]
7. <<E2C>> /EESMR - Energy Efficient State Machine Replication./
   *Middleware 2023*.
   *Adithya Bhat*, Akhil Bandarupalli, Manish Nagaraj, Saurabh Bagchi, Aniket Kate, Michael Reiter. [[https://dl.acm.org/doi/10.1145/3590140.3592848][conference]] [[https://arxiv.org/abs/2304.04998][eprint]]
8. <<Apollo>><<Artemis>> /The unique chain rule and its applications./
   *Financial Cryptography 2023*.
   *Adithya Bhat*, Akhil Bandarupalli, Saurabh Bagchi, Aniket Kate, Michael Reiter.
   [[https://fc23.ifca.ai/preproceedings/138.pdf][pre-conference]] [[https://doi.org/10.1007/978-3-031-47754-6_3][conference]] [[https://eprint.iacr.org/2021/180][eprint]] [[https://github.com/adithyabhatkajake/libchatter-rs][code]]
9. <<OptRand>> /OptRand - Optimistically Responsive Reconfigurable Distributed Randomness./
   *NDSS 2023*.
   *Adithya Bhat*, Nibesh Shrestha, Aniket Kate, Kartik Nayak.
   [[https://www.ndss-symposium.org/ndss-paper/optrand-optimistically-responsive-reconfigurable-distributed-randomness/][conference]] [[https://eprint.iacr.org/2022/193][eprint]] [[https://github.com/nibeshrestha/optrand][protocol code]] [[https://github.com/libdist-rs/optrand-rs][crypto code]] [[https://www.youtube.com/watch?v=6DH2bGXP3-4][video]]
10. <<OpenSquare>> /OpenSquare: Decentralized Repeated Modular Squaring Service./
    *CCS 2021*.
    Sri Aravinda Krishnan Thyagarajan, Tiantian Gong, *Adithya Bhat*, Aniket Kate, Dominique Schroder.
    [[https://dl.acm.org/doi/10.1145/3460120.3484809][conference]] [[https://eprint.iacr.org/2021/1273][eprint]] [[https://github.com/verifiable-timed-signatures/OpenSquare][code]]
11. <<RandPiper>> /RandPiper – Reconfiguration Friendly Random Beacons with Quadratic Communication./
    *CCS 2021*.
    *Adithya Bhat*, Nibesh Shrestha, Aniket Kate, Kartik Nayak.
    [[https://dl.acm.org/doi/abs/10.1145/3460120.3484574][conference]] [[https://eprint.iacr.org/2020/1590.pdf][eprint]] [[https://github.com/zhtluo/randpiper-rs][code]]
12. <<Reparo>> /Reparo - Publicly Verifiable Repair Layer for any Blockchain./
    *FC 2021*.
    Sri Aravinda Krishnan Thyagarajan, Adithya Bhat, Bernardo Magri, Daniel Tschudi, Aniket Kate.
    [[https://fc21.ifca.ai/papers/119.pdf][conference]] [[https://arxiv.org/abs/2001.00486][eprint]]
13. <<VTS>> /Verifiable Timed Signatures for Blockchains./
    *CCS 2020*.
    Sri Aravinda Krishnan Thyagarajan, Adithya Bhat, Guilio Malavolta, Nico Dottling, Aniket Kate, Dominique Schroder.
    [[https://dl.acm.org/doi/10.1145/3372297.3417263][conference]] [[https://eprint.iacr.org/2020/1563.pdf][eprint]] [[https://github.com/verifiable-timed-signatures/liblhtlp][code]]

* Patents
#+begin_export latex
\vspace{0.5em}
#+end_export
1. /Accountable Decentralized Anonymous Payments./ United States Patent Application 20240265373. [[https://www.freepatentsonline.com/y2024/0265373.html][patent]].
2. /Fast sync blockchain system and method./ United States Patent Application WO2024026321A1. [[https://patents.google.com/patent/WO2024026321A1/en][patent]].
3. /A system for partially synchronous scalable blockchains./ United States Patent Application WO2024233453A1. [[https://patentimages.storage.googleapis.com/06/d1/cc/9b924b543965ac/WO2024233453A1.pdf][patent]]
* Tech Reports
1. <<fps>> FPS: Flexible Payment Systems.
   *Adithya Bhat*, Srinivasan Raghuraman, Panagiotis Chatzigiannis, Duc V Le, Mohsen Minaei.
   [[https://eprint.iacr.org/2025/2095][eprint]]
1. <<FHE-sok>> SoK: /Fully-homomorphic encryption in smart contracts./ *Poster - FHE.org workshop*.
   Daniel Aronoff, *Adithya Bhat*, Panagiotis Chatzigiannis, Mohsen Minaei, Srinivasan Raghuraman, Robert M. Townsend, Nicolas Xuan-Yi Zhang.
   [[https://eprint.iacr.org/2025/527.pdf][eprint]]
3. <<Leto>> /Leto - Partially Synchronous Unique Chains made flexible./ *Adithya Bhat*, Saurabh Bagchi, Aniket Kate, Michael Reiter. [[https://github.com/libdist-rs/leto-rs][code]]
4. <<UTT>> /UTT: Decentralized Ecash with Accountable Privacy./ *Science of Blockchain Conference 2023*. Alin Tomescu, Adithya Bhat, Benny Applebaum, Ittai Abraham, Guy Gueta, Benny Pinkas, and Avishay Yanai. [[https://eprint.iacr.org/2022/452][eprint]] [[https://github.com/definitelyNotFBI/utt][code]]
5. <<TransNet>> /Transitive Network - A Tokenless IOU-based Credit Network./ *Cryptocurrency Implementers Workshop, FC 2019.* *Adithya Bhat*, Pedro Moreno Sanchez, Aniket Kate. [[https://github.com/pedrorechez/transitivenetwork][code]]
* Software Artifacts
1. Developed a synchronous networking library to implement SMR protocols. [[https://github.cowwm/adithyabhatkajake/libchatter-rs][code]] @@latex: \hfill @@ (Rust)
2. Implemented Apollo [[[Apollo]]] (protocol node, normal client and special client) using the Rust networking library. [[https://github.com/adithyabhatkajake/libchatter-rs][code]] @@latex: \hfill @@ (Rust)
3. Implemented Sync HotStuff (normal protocol node, round robin protocol node, client) using the Rust networking library. [[https://github.com/adithyabhatkajake/libchatter-rs][code]] @@latex: \hfill @@ (Rust)
4. Developed a plug-and-play framework using libp2p to run and simulate distributed system protocols. The framework provides interfaces to aid faster prototyping of distributed system protocols. [[https://github.com/adithyabhatkajake/libchatter/][code]] @@latex: \hfill @@ (Go-lang)
5. Implemented Sync HotStuff using the go networking library. [[https://github.com/adithyabhatkajake/libsynchs][code]] @@latex: \hfill @@ (Go-lang)
6. Implemented Apollo [[[Apollo]]] using the go networking library. [[https://github.com/adithyabhatkajake/libapollo][code]] @@latex: \hfill @@ (Go-lang)
7. Implementation of E2C [[[E2C]]]. [[https://github.com/adithyabhatkajake/libe2c-cpp][code]] @@latex: \hfill @@ (C++)
8. Developed a linearly homomorphic time-lock puzzle library. [[https://github.com/verifiable-timed-signatures/liblhtlp][code]] @@latex: \hfill @@ (C)
   #+begin_comment
    % \item[3.] Modified the Ethereum go client for Reparo~[3] to allow repairing of state. Code available at \href{https://github.com/adithyabhatkajake/reparo-geth}{https://githu\\b.com/adithyabhatkajake/reparo-geth}. \hfill \texttt{Go-lang}
    % \item[4.] Developed an auditing library based on {Compact proofs of retrievability}. Code available at \href{https://github.com/adithyabhatkajake/shacham-and-waters-scheme}{https://git\\hub.com/adithyabhatkajake/shacham-and-waters-scheme}. \hfill \texttt{C}
    % \item Analysis of Paging and Caching overheads in the Linux Kernel (Linux Kernel, C) [ 2017 ]
    % \item \textit{K-Rack} - A lightweight metadata encrypted steganographic filesystem (Linux Kernel, C) [ 2017 ]
    % \item Designing and building a Smart Mirror and its interface (Python) [ 2017 ]
    % \item \textit{Kompile} - A secure light-weight online code judge using modified runtimes and chroot jail (C, Django) [ 2017 ]
    % \item Deep4MalDroid: Android Malware detection using system call graphs, Genetic Algorithm for parameter selection and Naive Bayes for Detection (Python, C, Android) [ 2017 ]
    % \item \textit{TextWalker} - A natural language to RDF graph generator [Django, NLTK]
    % \item fMRI analysis using General Linear Model (R) [ 2017 ]
    % \item A comparative analysis of Fast Fourier Transform using GPU and CPU. We find that 1-D FFT is faster on a CPU than on a GPU. (CUDA, OpenCL) [2017]
    % \item \textit{Daedalus} - A tool implementing the attacks on RSA as proposed in Dan Boneh's survey paper \textit{20 years of attacks on RSA} (Python) [ 2016 ]
   #+end_comment
* Talks
# 2. Coin-tossing. @@latex: \hfill @@ /(Duke University - CSXXX)/
# 2. Consensus number of a cryptocurrency. @@latex: \hfill @@ /(Purdue University - CSXXX)/
1. Attacking and Improving the Tor Directory Protocol. @@latex: \hfill @@ /(RWC 2025)/
2. A study of practical BFT systems. @@latex: \hfill @@ /(Supra Team)/
3. A study of practical BFT systems. @@latex: \hfill @@ /(Espresso Systems)/
4. A study of practical BFT systems. [[https://doi.org/10.4230/DagRep.14.9.22][abstract]] @@latex: \hfill @@ /(Next Generation Secure Distributed Computing Seminar, Dagstuhl)/
5. OptRand, an optimistically responsive distributed random beacon protocol. [[https://www.youtube.com/watch?v=gtmOLG7lSVI&list=PLaJEOSRGBY4zhVg-eaw1IcsbdjJ0VEprq&index=3][video]] @@latex: \hfill @@ /(Web3 Randomness Workshop)/
6. Reconfiguration-friendly Byzantine Fault-tolerant Distributed randomness. [[https://adithyabhatkajake.github.io/assets/presentations/KU-Leuven-RandomBeacons.pptx][slides]] @@latex: \hfill @@ /(KU Leuven)/
7. Unique Chain Rule and its applications. [[https://adithyabhatkajake.github.io/assets/presentations/Unique-Chain-Rule-Applications.pptx][slides]] @@latex: \hfill @@ /(FC 2023)/
8. Reconfiguration-friendly Byzantine Fault-tolerant Distributed randomness. [[https://adithyabhatkajake.github.io/assets/presentations/BU-RandomBeacons.pptx][slides]] @@latex: \hfill @@ /(Boston University)/
9. Flexible State Machine Replication. [[https://adithyabhatkajake.github.io/assets/presentations/Midwest-crypto-day-Lightning-Talk.pptx][slides]] @@latex: \hfill @@ /(Midwest Crypto Day - Lightning session)/
10. OptRand - Optimistically Responsive Reconfigurable Distributed Randomness. [[https://www.youtube.com/watch?v=6DH2bGXP3-4][video]] @@latex: \hfill @@ /(NDSS 2023)/
11. FastSync: Using the future to verify the past. [[https://www.youtube.com/watch?v=kCqrd1MQ1no&t=3341s][video]] @@latex:\hfill @@ /(CESC 2022)/
12. RandPiper - Reconfiguration friendly random beacons with quadratic communication. @@latex:\hfill @@ /(CCS 2021)/
13. Reparo - Publicly Verifiable Repair Layer for any blockchain. [[https://youtube.com/watch?v=jV_Pjc17eWY][video]] @@latex: \hfill @@ /(FC 2021)/
14. Transitive network - A tokenless IOU-based Credit Network. Cryptocurrency Implementers Workshop. @@latex: \hfill @@ /(FC 2019)/
* Academic Service
- Program Committee:
  - 2026: FC, CCS, ACNS, Usenix Security
  - 2025: FC, CCS, CVC
  - 2024: CCS
- Reviewer for
  - 2024: ACM TOPS, Journal of Cryptology
  - 2023: SOSP AEC, IET
- External Reviewer for
  - 2025: ITCS, Crypto
  - 2024: IEEE S & P
  - 2023: CCS, IET, Middleware, IEEE S & P
  - 2022: CCS, PODC, IEEE S & P, CESC
  - 2021: AFT, FC, PODC, IEEE S & P
  - 2020: Usenix Security, IEEE S & P
  - 2019: NDSS
* 02-CV Tasks :noexport:
** DONE 📝 Usenix Security PC
CLOSED: [2025-09-02 Tue 22:54]
Created: [2025-08-12 Tue]
** DONE 📝 Lite-PoT CCS Acceptance
CLOSED: [2025-09-02 Tue 22:54]
Created: [2025-08-12 Tue]
** TODO 📝 Add Defi 26 acceptance of SoK on homomorphic smart contracts
Created: [2026-01-20 Tue]
** TODO 📝 Add FastSync Eprint
SCHEDULED: <2026-01-29 Thu 20:00>
Created: [2026-01-29 Thu]
** TODO 📝 Defi 2026 Acceptance
Created: [2026-02-02 Mon]
** TODO 📝 WTSC 2026 Acceptance
Created: [2026-02-02 Mon]
** TODO 📝 Add FastSync Eprint
Created: [2026-02-02 Mon]
https://arxiv.org/abs/2601.21286
